### PR TITLE
Google Profiles

### PR DESCRIPTION
**Pull request by falko**
Merge files from https://github.com/camunda-community-hub/camunda8-greenfield-installation/tree/main/google

FYI @rob2universe @upgradingdave

### CODE REVIEW

**Comment by falko** [comment]
I'll try relative paths instead of `$(helmProfilesDir)` or `$(root)`...

**Comment by falko** [comment]
Since having an `all` target is just a convention and `make` actually just runs the first target in a file, we could call the first target in a generic profile differently.

**Comment by falko** [comment]
If we would actually follow [the conventions](https://www.gnu.org/software/make/manual/make.html#Standard-Targets) we should probably be using `install`.

**Comment by falko** [comment]
Still getting some warnings:
```sh
$ make kube-metrics-all 
../../include/camunda.mk:102: warning: overriding recipe for target 'url-grafana'
../../metrics/metrics.mk:21: warning: ignoring old recipe for target 'url-grafana'
../../include/camunda.mk:106: warning: overriding recipe for target 'open-grafana'
../../metrics/metrics.mk:33: warning: ignoring old recipe for target 'open-grafana'
```

**Comment by falko** [comment]
The sub-make approach causes troubles:

- When Nginx installs fine but Camunda fails, it is not possible to run just `make camunda` again. Re-running inside the generic folder `ingress-nginx` also doesn't work because the config is in Makefile in google/ingress-nginx`
- Also the path to the values file must be relative to the sub-make working dir, which is at least confusing

This leads us to avoiding sub-make and using include only with above suggestions

**Comment by falko** [comment]
Found some resources on avoiding sub-make:
http://sites.e-advies.nl/nonrecursive-make.html
https://github.com/dmoulding/boilermake

**Comment by upgradingdave** [comment]
Hi @falko - I merged this branch to PR #36. I plan to regression test before the end of the week. I'll close this PR as soon as it's tested.

**Comment by upgradingdave** [comment]
Hi @falko, this has been merged and tested in #36

**Pull request closed without merging**
