### PR TITLE
Ingress kind

### PR DESCRIPTION
**Pull request by plungu**
Added ingress to kind and extended the profile to use most C8 components

### CODE REVIEW

**Comment by falko** [comment]
Hi @plungu,

thank you for you PR. I find it a little hard to review this. Would you have a chance to rebase this?

Cheers,
Falko

**Comment by falko** [comment]
Dependency for https://github.com/camunda-community-hub/camunda8-greenfield-installation/pull/4

**Review by falko — CHANGES_REQUESTED** [review]

**Comment by falko** [comment]
@plungu we should get this done before https://github.com/camunda-community-hub/camunda8-greenfield-installation/issues/3 happens

**Comment by upgradingdave** [comment]
Hi @plungu, I merged this into #36. 

I still need to merge your latest from the `kind-zeebe-gateway-ingress`

Thanks!

**Pull request closed without merging**
